src/App.css
src/App.js

Fix the search field and icon in the nav bar

testing out a changing of search field

---

src/App.css
src/App.js
src/assets/Dashboard.css
src/assets/Footer.css
src/assets/Settings.css
src/assets/UserProfile.css
src/components/Dashboard.jsx
src/components/Footer.jsx
src/components/Settings.jsx
src/components/UserProfile.jsx

i've changed some class components to functional components because i'm comfortable in working with functional components.
Colours you might not like so feel free to make any change..

light-dark mode applied

---

src/App.css
src/assets/Admin.css
src/assets/Dashboard.css
src/assets/Footer.css
src/assets/Profile.css
src/assets/Settings.css
src/assets/UserProfile.css
src/components/Dashboard.jsx
src/components/Settings.jsx
src/components/UserProfile.jsx

CSS changes for responsive behavior.

[update] - CSS changes for responsive behavior

---

src/assets/Dashboard.css
src/assets/Settings.css
src/assets/UserProfile.css

Suggested color-theme for the dark mode:
header background-color: #222831
header text color: #FFD369
background-color: #EEEEEE
text color: #393E46
Let me know what you think :)

added dark-mode colors with higher contrast

---

src/index.js

with this commit the issue #24 will be resolved

#24 Removed index.css from index.js

---

package-lock.json
src/App.js

added accessible name to buttons in the top bar

bugfix: added accessible name to buttons in the top bar

---

CONTRIBUTORS.md
src/App.js

added image logo at top nav and removed text logo

#44 bug solved

---

package-lock.json
package.json
src/assets/SideNav.css
src/components/SideNav.jsx

Added hamburger menu in sidenav bar.

Added hamburger menu in sidenav bar. 

---

src/App.css
src/App.js

Stays at the top of viewport on scroll. My OS is Windows 10 and I tried it on Mozilla Firefox and Chromium. Let me know if this is okay :)

Possible navbar fix

---

index.js
package-lock.json
package.json

this how the fullstack should work the index.js will be the server while having a different folder to hold all your api end point and DB e.g App

Adding server

---

src/assets/SideNav.css
src/components/SideNav.jsx

- Changes in files:
- SideNav.jsx
- SideNav.css
- Added Material UI Icons to SideNav component
- Removed unused functions and state hook

issue #60 - Added MUI icons to SideNav component

---

CONTRIBUTORS.md

Fixed contributors markdown file table; added a very important name to the list...
I think it's ok that I did this without raising an issue first? I guess we'll find out...

fixed contributors markdown file table; added a very important name to the list

---

src/App.css
src/assets/Post.css
src/components/Post.jsx

Closes #58
@gbowne1 
I prepered feature of creating new post. `Add Photo` and `Add Video` are clickable and enable user to send it's own photo or video. `Add mood` is not finished because I don't know if it match a concept. I think it could add some mood to post like on facebook.
At this moment submiting post does nothing, I don't know how it should be handled.

Completed Post.jsx component

---

CONTRIBUTORS.md
src/App.css
src/assets/Settings.css
src/components/Settings.jsx

@gbowne1 
I fixed accesibility by changing main text color to more contrasting one (I did for whole app, because problem was the same on every page) and by including tabbable switches from MUI.
Also changed Settings.jsx component structure to better aligned.
Fixes #40
Manually
**Test Configuration**:
- Hardware: ----
- Operating System: ----
- Toolchain: ----
- Browser: ----
- SDK: ----

Update of Settings.jsx component

---

src/App.js
src/assets/Footer.css

[BUG] All components are rendering to view #11
Ok so basically I removed the components that were located directly on .Section-app and added the routes there instead. this way now only the component that matches the route will be rendered in .Section-app, by default this will be the Dashboard component.
I also wrapped the header logo, settings and user menu icons with anchor tags that will redirect to "/", "/settings"  and "/profile" respectively. 
Finally I updated some css rules on Footer-footer a. These rules where directly on all <a> tags of the app, and would have a applied for example a margin-top of 18px to all links of the page. Now this will affect only the links inside the footer.

All components rendering

---

src/App.js

Moved SideNav component ouside the Router as discussed.
Screenshots of app:
Screenshot of app with opened SideNav:

Moved SideNav component outside the Router.

---

src/App.js

There are currently 2 Routers #92 fix.
Removed the redundant Router. Also added the NotFound component to the "*" route.
Screenshot of app:
Screenshot of app on some non existing route showing 404 Not Found component:

There are 2 Routers fix.

---

src/App.js

This PR fixes #104 
I have changed the route for `<UserProfile>` component to `user-profile` and `<Profile>` component to `profile`
Also formatted the code.
Waiting for your review @gbowne1

fix:fixed routes for user profile

---

src/components/TopNav.jsx

Imported icons.
Added functions to handle the click of
menu items. Added styles for menu icons.

Added icons and menu items to dropdown menu.

---

src/App.js
src/components/CustomAlert.jsx
src/components/Login.jsx
src/components/TopNav.jsx
src/utils.js

[TODO] App has no user registration or login functionality #8
Ok so I've recreated the Login component. I added some hardcoded testuser credentials to log in.
Test user credentials:
- username: "testuser1".
- email: "testuser@gmail.com"
- password: "Testpass1!"
Now it looks like this:
The component has username, email and password fields. It has validation in all these fields and also helper texts for each field.
I added a show/hide button for the password field. Also a remember me checkbox which if set will make sure the user
doesn't have to input credentials the next time he visits the site.
Both login and register are working with the localStorage. 
If the user clicks the "Register here!" the form switches to a register form. In order to register the user has to add credentials that …

Create login/register component

---

src/App.js
src/components/Login.jsx

Add current theme to Login component #116
Ok so I've updated the Login component to make use of the light and dark themes present on the rest of the app.
The current light version looks like this:
The dark version looks like:
I also added a switch panel on top of the form in order to control the theme.

Add theme to login

---

src/components/Login.jsx

Fix error: Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p> #118
Fix for the above issue, after updating to p elements the errors are gone:

Replaced p elements with span elements.

---

CONTRIBUTORS.md
TODO.md
package-lock.json
package.json

This PR adds more contributors to the CONTRIBUTORS.md
Suggest adding this to the other files:
- AUTHORS.md
- ACKNOWLEDEMENTS.md
Also look at adding to CODEOWNERS the most active contributors

Add contributors to CONTRIBUTORS.md

---

src/components/CloseButton.jsx
src/components/Dashboard.jsx
src/components/Friends.jsx
src/components/Profile.jsx
src/components/Settings.jsx
src/components/UserProfile.jsx

[TODO] Close X Icon missing from other components #128
Created a CloseButton component. Replaced the old close button with CloseButton component on Dashbaord, Friends, Profile, UserProfile components. Added CloseButton to Settings component.
I think this covers all the components that needed this type of work. If I missed some please write it in a comment and I can make another commit.

Add close icon

---

src/App.js
src/assets/Events.css
src/assets/SingleEvent.css
src/components/Events.jsx
src/components/SingleEvent.jsx
src/variables.css

[TODO] Add initial Events component. #132
Added the initial component UI following the wireframe on the issue. The UI looks like this right now:

Add initial events component

---

src/App.js
src/assets/Feedback.css
src/components/Dashboard.jsx
src/components/Events.jsx
src/components/Feedback.jsx
src/components/Friends.jsx
src/components/NotFound.jsx
src/components/Post.jsx
src/components/Profile.jsx
src/components/Settings.jsx
src/components/SideNav.jsx
src/components/SingleEvent.jsx
src/components/TopNav.jsx
src/components/UserProfile.jsx

I created feedback modal which is accessible on /feedback route. Modal is on top of the rest of app and has two buttons (`Go back`, `Go to GitHub`) and link to contribute documentation. Also added few fixes in app to match this solution.
`Go back` - switches route to previous one
`Go to GitHub` - leads to project repository, link opens in new tab, first tab stays the same with modal open.
Fixes #125
Manually

Feedback modal

---

src/components/Friends.jsx

I had some problems with the code in this component, especially adding cards to the Friends component panel so this 
will need quite a bit of work.  
My problems were trying to get cards to be 200px wide x 350px high total with 5-6 cards per row.  I was only able to get one card.
I removed the Suggested Friends and Friends Request panel in this commit/PR cycle.  Perhaps we can add other 
Includes removing other panels from within the coponent.
If anyone has any other suggestions on how to add cards.

This commit adds minor changes to Friends.jsx

---

.vs/tasks.vs.json
package-lock.json

i have updated the task.json file

#162 fixed this bug

---

src/App.js
src/pages/Login/Login.css
src/pages/Login/Login.jsx

Hello, I have worked on the issue on creating a modal box for accepting cookies from user.
Here is the screenshot of the output. And when ever a user refresh a page then we wait for 3seconds and then this modal box will popup. In the future we can handle this modal if he accepted cookies or not.

Worked On the issue : Add method to accept cookies #54

---

src/pages/Profile/Profile.jsx
src/pages/UserProfile/UserProfile.css
src/pages/UserProfile/UserProfile.jsx

The UserProfile.jsx did not have very good code in it so I added code that will be a bit more useful.  This should make it easier to both complete fix the UserProfile.jsx
I added prop-types, useNavigate, useState, useEffect, and persisted some LocalStorage code.  I was on the fence about using LocalStorage for user profile stuff.
I will take any ideas from here.
The CSS will need to be fixed as well.
The component 404's now but will be a lot easier to fix and complete. I think we can agree that the original compnent code was not very good

Fixing some issues with UserProfile.jsx and Profile.jsx

---

src/pages/Events/CreateEventModal/CreateEventModal.jsx
src/pages/Events/CreateEventModal/__test___/CreateEventModal-flow.test.js
src/pages/Events/CreateEventModal/__test___/CreateEventModal-initial-state.test.js
src/pages/Events/CreateEventModal/__test___/CreateEventModal-validation.test.js
src/pages/Events/Events.jsx
src/pages/Events/SingleEvent/__test__/SingleEvent-buttons.test.js
src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js
src/pages/Events/__test__/Event-attendance-filter.test.js
src/pages/Events/__test__/Event-initial-state.test.js
src/pages/Login/Login.jsx
src/pages/Login/__test__/Login-alert-message.test.js
src/pages/Login/__test__/Login-flow.test.js
src/pages/Login/__test__/Login-initial-state.test.js
src/pages/Login/__test__/Login-validation.test.js
src/utils/renderComponent.js

I've added some refactoring of tests, created some util functions and removed some unnecessary console logs from some components.
Review should be pretty straight forward, just run the unit tests :)

Refactor tests

---

.eslintrc
package.json
src/App.js

I deleted error at `.eslintrc` config file to not throw error on wrong quotes and lack of semicolons. I think that since `.prettierrc` has this in it's config we doesn't have to use it in `.eslintrc`. My IDE automatically formates code based on `.prettierrc` on save. If it's not the case in your IDE @gbowne1 @manuel12 I added "format" script into `package-json`
`.package-json`
This script should be run whenever you want to format all files according to prettier styles. I didn't run this script because it would change 111 files and it would made important changes non visible. I can make another PR with formatted code.
We should also run this command before pushing changes to GitHub, so formatting wouldn't appear on files on another PR, but on PR where such files were changed.
Fixes #182

Updated eslint config to omit redundant errors

---

README.md

Our README.md has not been the greatest or the most descriptive or helpful. 
I have added more context to the README and organized it better as well as added Sheilds and Badges from shields.io

Adding better README.md

---

client/src/components/Panel/Panel.css
client/src/components/Panel/Panel.jsx
client/src/pages/HelpCenter/HelpCenter.jsx

Fixed Issue #230 
Here are the screenshots:-

[Bug]: Fix the Help component's CSS #230

---

client/src/pages/Profile/Profile.css
client/src/pages/Profile/Profile.jsx

Fixed issue #199 
Added the modal in Profile.jsx and the respective styles in Profile.css
I forked and cloned the repo again and made the necessary changes.
Hoping this will be merged successfully

feat: Create Profile Modal

---

client/src/components/CookieModal/CookieModal.css
client/src/components/CookieModal/CookieModal.jsx
client/src/pages/Login/Login.css

This is a fix for: https://github.com/gbowne1/reactsocialnetwork/issues/221
I have changed the bg color of login input in order to make it more readable even with the label texts.
It now looks like this: 
I also included on the commit the removal of Cookie Modal styling rules from Login.css and imported them and added them to CookieModal.css

Login panel css issue 

---

client/package.json
client/src/pages/Events/CreateEventModal/CreateEventModal.jsx
e2e/cypress.config.js
e2e/cypress/e2e/events.cy.js
e2e/package-lock.json
e2e/package.json

This fixes #259 and #260.
I updated cypress config to be work correctly now that cypress has been updated. I also added a prackage.json to the e2e folder with the info about cypress version and cypress scripts. I removed cypress package and scripts from the client folder's package.json. 
I also refactored event's tests as they were currently failing, now they all pass.

Fix cypress config error and CreateEventModal has CSS import error.

---

client/src/pages/Events/CreateEventModal/__test___/CreateEventModal-flow.test.js
client/src/pages/Events/SingleEvent/__test__/SingleEvent-buttons.test.js
client/src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js
client/src/pages/Events/__test__/Event-attendance-filter.test.js
client/src/pages/Events/__test__/Event-initial-state.test.js
client/src/pages/Login/__test__/Login-alert-message.test.js
client/src/pages/Login/__test__/Login-flow.test.js
client/src/utils/renderComponent.js

I updated the unit tests according to: #263

Update unit tests

---

docs/ReactSocialNetwork.drawio

This will be useful for design.  You can open this by going to draw.io and opening the external template on your device.
I started with the Admin Dashboard.  Other pages need to be added, but this should be a good start.

This commit adds the start of a draw.io RSN template.

---

client/src/components/Panel/Panel.jsx
client/src/pages/Friends/Friends.jsx

BUG: propTypes Issue

---

client/src/index.jsx

Closes #287 
**_Renamed "index.js" to "index.jsx" and removed ReactStrictMode._**

Change /src/index.js to .jsx and remove Strict Mode

---

client/src/components/CookieModal/CookieModal.css
client/src/components/Post/Post.css
client/src/components/PostForm/PostForm.css
client/src/layouts/Footer/Footer.css
client/src/layouts/SideNav/SideNav.css
client/src/layouts/TopNav/TopNav.css
client/src/layouts/TopNav/TopNav.jsx
client/src/pages/AdminDashboard/Admin.Dashboard.css
client/src/pages/Dashboard/Dashboard.css
client/src/pages/Editor/Editor.css
client/src/pages/Editor/Editor.jsx
client/src/pages/Friends/Friends.css
client/src/pages/HelpCenter/HelpCenter.css
client/src/pages/HelpCenter/SubjectDetails.css
client/src/pages/NotFound/NotFound.css
client/src/pages/Post/Post.css
client/src/pages/Profile/Profile.css
client/src/pages/Register/Register.css
client/src/pages/Settings/Settings.css
client/src/pages/Terms/Terms.jsx
client/src/pages/UserProfile/UserProfile.css
client/src/pages/UserProfile/UserProfile.jsx
client/src/utils/getFromLocalStorage.js

This PR solves: https://github.com/gbowne1/reactsocialnetwork/issues/289
There was no real issue with the `getFromLocalStorage`. It simply logged to the console when it didn't find data with a certain key. Whenever clearing localStorage this would then log whatever keys where not found before initializing them. I removed  the confusing console log and added to the JS doc that it will return null when data is not found.

Local storage issue

---

client/src/utils/fetchUserData.js
e2e/cypress.config.js
e2e/cypress/e2e/api/friends-api.cy.js
e2e/cypress/e2e/api/post-api.cy.js
e2e/cypress/e2e/api/user-api.cy.js
e2e/cypress/e2e/ui/cookie-modal.cy.js
e2e/cypress/e2e/ui/events.cy.js
e2e/cypress/e2e/ui/login.cy.js
e2e/cypress/e2e/ui/posts.cy.js
e2e/cypress/e2e/ui/top-nav.cy.js
e2e/cypress/support/commands.js
server/database.js
server/routes/friend-requests/acceptFriendRequest.js
server/routes/friend-requests/createFriendRequest.js
server/routes/friend-requests/getFriendRequestsReceived.js
server/routes/friend-requests/getFriendRequestsSent.js
server/routes/friend-requests/getUserFriends.js
server/routes/friend-requests/rejectFriendRequest.js
server/routes/friend-requests/unfriend.js
server/routes/posts/deleteTestPosts.js
server/routes/users/deleteTestUsers.js

This PR includes the friendship-related  backend actions and APIs + api tests.
The added api routes are:
* Friends routes:
* `GET /api/users/:userId/friends` -> Get all friends from a user.
* `GET /friend-requests/received/:userId`-> Get pending friend requests received by the user.
* `GET /friend-requests/sent/:userId`-> Get pending friend requests sent by the user.
* `POST /api/friend-requests/`-> Send a friend  request.
* `POST /api/friend-requests/accept/:requestId`-> Accept a friend  request.
* `POST /api/friend-requests/reject/:requestId`-> Reject a friend  request.
* `DELETE /friends/:friendshipId`-> Unfriend a  specific user.

Friends back end

---

docs/CONTRIBUTING.french.md

@gbowne1 
#235 This is a French translation for the _**Contributing.md**_ file.

adding CONTRIBUTING.french.md

---

client/package-lock.json
client/src/pages/Login/Login.jsx

Improved error handling for network requests.
Added client-side validation for form fields.
Refactored snackbar handling for clarity.
Renamed a function and improved code structure.

updating log in page
